import os, sys, random, time, math

# This imports from a file that will be present in the
# grading system. No need to alter for local testing -
# if the file isn't present then these lines are skipped
try:
    from compile_with_soln import grader_stub

    grader = grader_stub()
except:
    pass

N = 0
neighbors_cache = []

# ----------------------------------------
# This function (which will be compiled with our code
# when submitted to the grading system) takes the index
# of a data point (in 0..N-1) and returns a list of
# indices of neighboring points

# grader.get_neighbors(i);
# ----------------------------------------


# ----------------------------------------
# For testing on your own system, you can call this function
# instead.  It builds an instance for which the optimal
# solution consists of a block of even-indexed points
# 0, 2, 4, ..., followed by a block of odd-indexed points
# 1, 3, 5, ... (note that the reversal of this is also
# equally optimal).
# ----------------------------------------

def get_neighbors_local(i):
    global N
    if i < 0 or i >= N:
        print("get_neighbors_local: Invalid point index!")
        sys.exit(0)
    if N % 2 == 1:
        print("get_neighbors_local: Please set N to an even value, since the test cases generated by this function have a structure depending on N being even (note that N doesn't need to be even for the real test cases).")
        sys.exit(0)
    answer = []
    answer.append(i + 1 - (i % 2) * 2)
    for j in range(N // 2):
        nbr = i % 2 + j * 2
        if nbr != i and abs(nbr - i) < N // 2:
            answer.append(nbr)
    return answer

# Shouldn't need to alter this function except to switch
# from local grader function to grader.get_neighbors()
# when you submit.
def getNeighbors(i):
    try:
        return grader.get_neighbors(i)
    except:
        return get_neighbors_local(i)


def squared_wire_length_objective(V):
    global N
    where = [None] * N
    for i in range(N):
        where[V[i]] = i
    total = 0
    for i in range(N):
        # Use our neighbors_cache instead of calling getNeighbors(i)
        for j in neighbors_cache[i]:
            d = where[i] - where[j]
            total += d * d
    return total / 2

def buildPos(order):
    pos = [0] * len(order)
    for idx, node in enumerate(order):
        pos[node] = idx
    return pos

def deltaSwap(order, pos, i, j):
    global neighbors_cache
    nodeI = order[i]
    nodeJ = order[j]
    deltaSum = 0
    # Use neighbors_cache here instead of getNeighbors
    for neighbor in neighbors_cache[nodeI]:
        if neighbor == nodeJ:
            continue
        deltaSum += ((j - pos[neighbor]) ** 2 - (i - pos[neighbor]) ** 2)
    for neighbor in neighbors_cache[nodeJ]:
        if neighbor == nodeI:
            continue
        deltaSum += ((i - pos[neighbor]) ** 2 - (j - pos[neighbor]) ** 2)
    return deltaSum / 2.0

def greedy_initial_order():
    global N, neighbors_cache
    order = []
    remaining = set(range(N))
    current = random.choice(list(remaining))
    order.append(current)
    remaining.remove(current)

    while remaining:
        best_next = max(
            remaining,
            key=lambda x: sum(1 for y in order if y in neighbors_cache[x])
        )
        order.append(best_next)
        remaining.remove(best_next)
    return order

def main():
    global N, neighbors_cache
    # The value for N is set in the grading system through an
    # environment variable, if present.  If not present, feel
    # welcome to set N to any value you want for local testing.
    try:
        N = int(os.environ["N"])
    except:
        N = 20

    # Below is the part of main() you should modify.
    # (you are welcome to write other functions above
    # and call them here, but all your code should be
    # submitted in this one file).
    # This code (which you should replace) just tries
    # random orderings (random permutations of 0..N-1)
    # until more than 28 seconds have elapsed, then
    # prints out whichever achieves the lowest objective
    # value.

    # NOTE: Please make sure to not change the amount
    # of time you should wait before printing - any
    # longer and you run the risk of your code timing
    # out for the testcase and not receiving credit.

    startTime = time.time()
    timeLimit = 28.0  # Time budget for Python submissions.

    # Build a global adjacency cache once
    neighbors_cache = []
    for i in range(N):
        neighbors_cache.append(getNeighbors(i))

    # Start with a greedy initial solution
    currentOrder = greedy_initial_order()
    pos = buildPos(currentOrder)
    currentCost = squared_wire_length_objective(currentOrder)
    bestOrder = currentOrder[:]
    bestCost = currentCost

    # Simulated Annealing parameters
    temperature = 1000.0
    cooling_rate = 0.999
    iterations = 0

    while time.time() - startTime < timeLimit:
        for _ in range(100):  # Batch of 100 iterations before checking time
            a = random.randint(0, N - 1)
            b = random.randint(0, N - 1)
            if a == b:
                continue
            if a > b:
                a, b = b, a
            d = deltaSwap(currentOrder, pos, a, b)

            if d < 0 or random.random() < math.exp(-d / temperature):
                currentOrder[a], currentOrder[b] = currentOrder[b], currentOrder[a]
                pos[currentOrder[a]] = a
                pos[currentOrder[b]] = b
                currentCost += d
                if currentCost < bestCost:
                    bestCost = currentCost
                    bestOrder = currentOrder[:]

            temperature *= cooling_rate
            iterations += 1

        # Check time only after a batch
        if time.time() - startTime >= timeLimit:
            break

    print(" ".join(map(str, bestOrder)))

if __name__ == "__main__":
    main()
