import os, sys, random, time

# This imports from a file that will be present in the
# grading system. No need to alter for local testing -
# if the file isn't present then these lines are skipped
try:
    from compile_with_soln import grader_stub

    grader = grader_stub()
except:
    pass

N = 0  # number of points


# ----------------------------------------
# This function (which will be compiled with our code
# when submitted to the grading system) takes the index
# of a data point (in 0..N-1) and returns a list of
# indices of neighboring points

# grader.get_neighbors(i);
# ----------------------------------------


# ----------------------------------------
# For testing on your own system, you can call this function
# instead.  It builds an instance for which the optimal
# solution consists of a block of even-indexed points
# 0, 2, 4, ..., followed by a block of odd-indexed points
# 1, 3, 5, ... (note that the reversal of this is also
# equally optimal).
# ----------------------------------------

def get_neighbors_local(i):
    global N
    if i < 0 or i >= N:
        print("get_neighbors_local: Invalid point index!")
        sys.exit(0)

    if N % 2 == 1:
        print(
            "get_neighbors_local: Please set N to an even value, since the test cases generated by this function have a structure depending on N being even (note that N doesn't need to be even for the real test cases).")
        sys.exit(0)
    answer = []
    answer.append(i + 1 - (i % 2) * 2)
    for j in range(N // 2):
        nbr = i % 2 + j * 2
        if nbr != i and abs(nbr - i) < N // 2:
            answer.append(nbr)
    return answer


# Shouldn't need to alter this function except to switch
# from local grader function to grader.get_neighbors()
# when you submit.
def getNeighbors(i):
    try:
        return grader.get_neighbors(i)
    except:
        return get_neighbors_local(i)

def squared_wire_length_objective(V):
    global N
    where = [None] * N
    # where[i] is the index in V at which data point i resides
    for i in range(N):
        where[V[i]] = i
    total = 0
    for i in range(N):
        for j in get_neighbors_local(i):  # Switch to grader.get_neighbors() when you submit
            d = where[i] - where[j]
            total += d * d
    return total / 2  # divide by 2 since we count each distance above twice

def buildPos(order):
    pos = [0] * len(order)
    for idx, node in enumerate(order):
        pos[node] = idx
    return pos

def deltaSwap(order, pos, i, j):
    nodeI = order[i]
    nodeJ = order[j]
    deltaSum = 0
    for neighbor in getNeighbors(nodeI):
        if neighbor == nodeJ:
            continue
        deltaSum += ((j - pos[neighbor])**2 - (i - pos[neighbor])**2)
    for neighbor in getNeighbors(nodeJ):
        if neighbor == nodeI:
            continue
        deltaSum += ((i - pos[neighbor])**2 - (j - pos[neighbor])**2)
    return deltaSum / 2.0

def main():
    global N
    # The value for N is set in the grading system through an
    # environment variable, if present.  If not present, feel
    # welcome to set N to any value you want for local testing.
    try:
        N = int(os.environ["N"])
    except:
        N = 20

    # Below is the part of main() you should modify.
    # (you are welcome to write other functions above
    # and call them here, but all your code should be
    # submitted in this one file).
    # This code (which you should replace) just tries
    # random orderings (random permutations of 0..N-1)
    # until more than 28 seconds have elapsed, then
    # prints out whichever achieves the lowest objective
    # value.

    # NOTE: Please make sure to not change the amount
    # of time you should wait before printing - any
    # longer and you run the risk of your code timing
    # out for the testcase and not receiving credit.

    startTime = time.time()
    timeLimit = 28.0  # Time budget for Python submissions.

    bestCost = -1
    currentOrder = list(range(N))
    random.shuffle(currentOrder)
    pos = buildPos(currentOrder)
    currentCost = squared_wire_length_objective(currentOrder)
    bestOrder = currentOrder[:]
    bestCost = currentCost

    # Outer loop: keep improving while there is time left.
    while time.time() - startTime < timeLimit:
        improved = False
        for _ in range(1000):
            if time.time() - startTime >= timeLimit:
                break
            a = random.randint(0, N - 1)
            b = random.randint(0, N - 1)
            if a == b:
                continue
            if a > b:
                a, b = b, a
            d = deltaSwap(currentOrder, pos, a, b)
            if d < 0:
                currentOrder[a], currentOrder[b] = currentOrder[b], currentOrder[a]
                pos[currentOrder[a]] = a
                pos[currentOrder[b]] = b
                currentCost += d
                improved = True
                if currentCost < bestCost:
                    bestCost = currentCost
                    bestOrder = currentOrder[:]
                break
        if not improved:
            currentOrder = list(range(N))
            random.shuffle(currentOrder)
            pos = buildPos(currentOrder)
            currentCost = squared_wire_length_objective(currentOrder)
            if currentCost < bestCost:
                bestCost = currentCost
                bestOrder = currentOrder[:]

    print(" ".join(map(str, bestOrder)))


if __name__ == "__main__":
    main()
